services:
  - type: web
    name: api-pica
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api-pica:app --host 0.0.0.0 --port $PORT
    plan: free